"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

// ─── Dynamic color system ────────────────────────────────────────────────────
//
// Colors are derived entirely from the data — no hardcoded category keywords.
// Each unique course *family* (e.g. "technology", "development", "web") gets its
// own hue, generated by evenly spacing hues around the HSL wheel. Courses within
// the same family share that hue but vary in lightness, giving a coherent but
// distinct palette per family regardless of what the courses are called.

// Generate N evenly-spaced hues (0–360), with a fixed offset so the first color
// isn't a harsh red.
function generateHues(n, offset = 200) {
  return Array.from({ length: n }, (_, i) =>
    Math.round((offset + (i * 360) / n) % 360)
  );
}

// Given a hue, return a small palette of shades (light fills, readable on white bg)
function hueToPalette(hue) {
  return [
    `hsl(${hue}, 70%, 88%)`,
    `hsl(${hue}, 65%, 80%)`,
    `hsl(${hue}, 60%, 72%)`,
  ];
}

// Build a { family → palette } map from all families found in the data
function buildFamilyPalettes(families: string[]) {
  const uniqueFamilies = Array.from(new Set(families));
  const hues = generateHues(uniqueFamilies.length);
  const map: Record<string, string[]> = {};
  uniqueFamilies.forEach((fam, i) => {
    map[fam] = hueToPalette(hues[i]);
  });
  return map;
}

// Extract the "family" of a course: strip trailing numbers / "solo" / "imd" etc.
// e.g. "Technology 3" → "technology", "Development 2" → "development",
//      "Creative Business Studio 1" → "creative business studio",
//      "Keuzevak 1 IMD" → "keuzevak"
const getFamily = (name) =>
  name
    .toLowerCase()
    .replace(/\s*(solo|imd)\s*/gi, " ")
    .replace(/\s+\d+\s*$/, "")
    .trim();

const getSemesterFromCalendar = (calendar) => {
  const last = parseInt(calendar?.match(/\d+/g)?.pop() || "1");
  return last % 2 === 0 ? "Semester 2" : "Semester 1";
};

const cleanTraject = (traject) =>
  (traject || "Unknown Trajectory")
    .replace(/\s*(voltijds|contacttraject)\s*/gi, "")
    .trim()
    .split(/\s+/)
    .filter((w, i, arr) => i === arr.lastIndexOf(w))
    .join(" ");

// ─── Build per-column row placement ─────────────────────────────────────────
//
// Rules:
//  • Every semester column is exactly ROWS_PER_SEMESTER rows tall (default 30).
//  • No gaps — courses pack tightly; study_load == gridRowSpan.
//  • Same-family courses align across columns: when a family is first seen it
//    claims a rowStart; subsequent columns snap their cursor forward to that
//    same rowStart before placing the course (only if the cursor hasn't already
//    passed it — we never go backwards, which would cause overlap).
//
// Result: { colKey → [ { course, rowStart, rowSpan } ] }
// colKey = `${yi}-${semKey}` (e.g. "0-Semester 1")

const ROWS_PER_SEMESTER = 30;

function buildLayout(structuredCourses) {
  const years   = Object.entries(structuredCourses);
  const semKeys = ["Semester 1", "Semester 2"];

  // First pass: sort courses within each column by family-name so related
  // families land near each other naturally across years.
  years.forEach(([, semesters]) => {
    semKeys.forEach((sk) => {
      if (semesters[sk]) {
        semesters[sk].sort((a, b) =>
          getFamily(a.course_name).localeCompare(getFamily(b.course_name))
        );
      }
    });
  });

  // familyAnchor: family → rowStart the first time we placed this family.
  // Used to align the same family in later columns.
  const familyAnchor = {};

  // placement: colKey → array of { course, rowStart, rowSpan }
  const placement = {};

  years.forEach(([, semesters], yi) => {
    semKeys.forEach((sk) => {
      const colKey = `${yi}-${sk}`;
      const list   = semesters[sk] || [];
      placement[colKey] = [];
      let cursor = 1; // 1-indexed, current free row in this column

      list.forEach((course) => {
        const fam  = getFamily(course.course_name);
        const span = course.study_load;

        if (familyAnchor[fam] !== undefined) {
          // Snap cursor forward to the anchor if we haven't passed it yet.
          // Never go backwards — that would overlap preceding courses.
          if (familyAnchor[fam] >= cursor) {
            cursor = familyAnchor[fam];
          }
        } else {
          // First time we see this family — record where it lands.
          familyAnchor[fam] = cursor;
        }

        // Safety: if cursor + span - 1 > ROWS_PER_SEMESTER the column is over-full;
        // just clamp to whatever space remains (data error, not a layout error).
        const rowStart = cursor;
        const rowSpan  = Math.min(span, ROWS_PER_SEMESTER - cursor + 1);

        placement[colKey].push({ course, rowStart, rowSpan });
        cursor += rowSpan;
      });
    });
  });

  return { placement, totalRows: ROWS_PER_SEMESTER };
}

// ─── Color assignment (fully dynamic, family-based) ──────────────────────────
//
// 1. Collect all families from the data.
// 2. Generate one hue per family via buildFamilyPalettes().
// 3. Within a family, each individual course name gets the next shade in that
//    family's palette, so siblings are visually grouped but still distinct.
function assignColors(structuredCourses) {
  const allFamilies = [];
  Object.values(structuredCourses).forEach((semesters) =>
    Object.values(semesters).forEach((courses) =>
      courses.forEach((c) => allFamilies.push(getFamily(c.course_name)))
    )
  );

  const familyPalettes  = buildFamilyPalettes(allFamilies);
  const familyShadeIdx  = {};
  const colorMap        = {};

  Object.values(structuredCourses).forEach((semesters) =>
    Object.values(semesters).forEach((courses) =>
      courses.forEach((c) => {
        if (colorMap[c.course_name]) return;
        const fam = getFamily(c.course_name);
        const pal = familyPalettes[fam];
        const idx = (familyShadeIdx[fam] || 0) % pal.length;
        familyShadeIdx[fam] = (familyShadeIdx[fam] || 0) + 1;
        colorMap[c.course_name] = { color: pal[idx], category: fam };
      })
    )
  );

  return colorMap;
}

// ─── Main Component ──────────────────────────────────────────────────────────
export default function CoursesPage() {
  const [courses, setCourses]   = useState({});
  const [layout, setLayout]     = useState(null);

  useEffect(() => {
    const raw   = localStorage.getItem("courses");
    const data  = raw ? JSON.parse(raw) : [];

    // Build structuredCourses (same logic as before, no sorting needed here –
    // order is handled by the global layout)
    const structured = {};
    data.forEach((course) => {
      if (!course.course_name) return;
      const traject  = cleanTraject(course.traject);
      if (traject === "Unknown Trajectory") return;
      const semester = getSemesterFromCalendar(course.calendar);
      if (!structured[traject]) structured[traject] = { "Semester 1": [], "Semester 2": [] };
      structured[traject][semester].push({
        course_name:    course.course_name,
        study_load:     parseInt(course.study_load),
        study_programs: course.study_programs || "",
        content:        course.content        || "",
      });
    });

    const colors = assignColors(structured);
    const lyt    = buildLayout(structured);

    // Attach color info to each course object
    Object.values(structured).forEach((semesters) =>
      Object.values(semesters).forEach((list) =>
        list.forEach((c) => {
          const ci = colors[c.course_name] || { color: "#fff", category: "default" };
          c.color    = ci.color;
          c.category = ci.category;
          c.family   = getFamily(c.course_name);
        })
      )
    );

    setCourses(structured);
    setLayout(lyt);
  }, []);

  if (!layout) return null;

  const { placement, totalRows } = layout;
  const semKeys = ["Semester 1", "Semester 2"];

  return (
    <div className="max-w-6xl mx-auto pt-5 min-h-screen">
      <h1 className="text-3xl font-bold mb-3">
        Cursusoverzicht{" "}
        {Object.entries(courses)[0]?.[0].replace("Schijf 1", " ") || ""}
      </h1>

      <div className="grid grid-cols-6 gap-4">
        {Object.entries(courses).map(([traject, semesters], yi) => (
          <div key={traject} className="mb-8 col-span-2 flex flex-col">
            <h2 className="text-2xl font-bold mb-4">
              Jaar {yi + 1}
            </h2>

            <div className="grid grid-cols-2 gap-4 flex-1">
              {semKeys.map((semKey) => {
                const colKey     = `${yi}-${semKey}`;
                const colEntries = placement[colKey] || [];
                return (
                  <div key={semKey} className="bg-gray-100 rounded flex flex-col p-0">
                    <h3 className="text-xl font-semibold mb-2">{semKey}</h3>

                    <div
                      style={{
                        display: "grid",
                        gridTemplateRows: `repeat(${totalRows}, 1fr)`,
                        gap: "4px",
                        height: "100%",
                      }}
                    >
                      {colEntries.map(({ course, rowStart, rowSpan }, idx) => (
                          <Link
                            key={idx}
                            href={`/course/${encodeURIComponent(course.course_name)}`}
                            className="p-2 shadow rounded block hover:shadow-lg transition group relative overflow-hidden"
                            style={{
                              gridRow: `${rowStart} / span ${rowSpan}`,
                              backgroundColor: course.color,
                              borderLeft: `3px solid ${
                                course.study_programs.length > 1 ? "#9ae6b4" : "#c084fc"
                              }`,
                            }}
                          >
                            <h2 className="font-bold text-sm leading-tight">
                              {course.course_name}
                            </h2>
                            <p className="text-xs text-gray-600 mt-0.5">
                              {course.study_load} SP
                            </p>

                            {course.content && (
                              <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-80 bg-gray-800 text-white text-xs p-3 rounded opacity-0 group-hover:opacity-100 transition pointer-events-none z-10">
                                {course.content}
                              </div>
                            )}
                          </Link>
                        ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
